version: 2.1
orbs:
  orb-tools: circleci/orb-tools@12.0
  ostorlab-circleci: {}

filters: &filters
  tags:
    only: /.*/

# Filter for release tags.
release-filters: &release-filters
  branches:
    ignore: /.*/
  tags:
    only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

jobs:
  command-test:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
workflows:
  test-deploy:
    jobs:
      - command-test:
          filters: *filters
      - orb-tools/pack:
          filters: *release-filters
      - orb-tools/publish:
          orb_name: ostorlab-circleci/ostorlab
          vcs_type: << pipeline.project.type >>
          pub_type: production
          requires:
            - orb-tools/pack
            - command-test
          context: orb-publishing
          filters: *release-filters
